name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push User Service
      - name: Build and push Docker image for User Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/user-service
          file: ./services/user-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      # Build and push Restaurant Service
      - name: Build and push Docker image for Restaurant Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/restaurant-service
          file: ./services/restaurant-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/restaurant-service:latest

      # Build and push Product Service
      - name: Build and push Docker image for Product Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/product-service
          file: ./services/product-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-service:latest

      # Build and push Notification Service
      - name: Build and push Docker image for Notification Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/notification-service
          file: ./services/notification-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

