name: Install Dependencies for Each Service

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies for user service
        run: |
          cd services/user-service
          pip install -r requirements.txt

      - name: Install dependencies for restaurant service
        run: |
          cd services/restaurant-service
          pip install -r requirements.txt

      - name: Install dependencies for product service
        run: |
          cd services/product-service
          pip install -r requirements.txt

      - name: Install dependencies for notification service
        run: |
          cd services/notification-service
          pip install -r requirements.txt
