name: Build and Test Services with Docker Compose

on:
  push:
    branches:
      - main  # or any other branch you want to trigger on
  pull_request:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation

      # Step 4: Build and run with Docker Compose
      - name: Build and run with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose up -d

      # Step 5: Run tests (if applicable)
      # Example: Test user-service is up
      - name: Test user-service is up
        run: |
          curl --fail http://localhost:5001/health || exit 1

      # Step 6: Shutdown Docker Compose
      - name: Shutdown Docker Compose
        run: docker-compose down
