name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use the latest version

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to latest version

    - name: Cache Docker layers
      uses: actions/cache@v3  # Updated to latest version
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and push Docker image for User Service
      uses: docker/build-push-action@v3  # Updated to latest version
      with:
        context: ./  # Context to current directory
        file: ./docker-compose.yml  # Use the right file path
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Health check for user-service
      run: |
        curl --fail http://localhost:5001/health || exit 1
