name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, productservice, notification-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ matrix.service }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME ./microservices-project/$IMAGE_NAME
        docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
