name: Install Dependencies for Each Service

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List repository structure (debugging)
        run: |
          echo "Listing the repository structure:"
          ls -R

      - name: Install dependencies for user service
        run: |
          cd SOA-Project/services/user-service
          pip install -r requirements.txt

      - name: Install dependencies for restaurant service
        run: |
          cd SOA-Project/services/restaurant-service
          pip install -r requirements.txt

      - name: Install dependencies for product service
        run: |
          cd SOA-Project/services/product-service
          pip install -r requirements.txt

      - name: Install dependencies for notification service
        run: |
          cd SOA-Project/services/notification-service
          pip install -r requirements.txt
